-- ==========================================
-- TABEL GALERI
-- ==========================================
CREATE TABLE IF NOT EXISTS galeri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Aktifkan RLS
ALTER TABLE galeri ENABLE ROW LEVEL SECURITY;

-- Tambah Policy: Izin Baca Publik
CREATE POLICY "Enable read access for all users" 
ON galeri FOR SELECT 
USING (true);

-- Seed Data Galeri
INSERT INTO galeri (image_url)
VALUES 
  ('https://images.unsplash.com/photo-1555597673-b21d5c935865?q=80&w=800'),
  ('https://images.unsplash.com/photo-1544098485-2a2ed6da40ba?q=80&w=800'),
  ('https://images.unsplash.com/photo-1576485290814-1c72aa4faa8e?q=80&w=800'),
  ('https://images.unsplash.com/photo-1593113598332-cd288d649433?q=80&w=800');
